/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  collections: {
    users: User;
    'page-configs': PageConfig;
    news: News;
    faqs: Faq;
    media: Media;
    'payments-admin': PaymentsAdmin;
    tokens: Token;
    feedback: Feedback;
    passwords: Password;
    stopPlay: StopPlay;
    taskfromusers: Taskfromuser;
    'login-logs': LoginLog;
    paymentlogs: Paymentlog;
    'binary-files': BinaryFile;
    'login-tracking': LoginTracking;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  globals: {};
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  role: 'admin' | 'editor' | 'user' | 'guest';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-configs".
 */
export interface PageConfig {
  id: string;
  type: 'Intelekt' | 'Opensvit' | 'Opticom' | 'Veles' | 'Mtknet';
  backgroundVideo?: string | Media | null;
  logo?: string | Media | null;
  logo_min_navigation?: string | Media | null;
  contract_pdf?: string | Media | null;
  telegram_id?: string | null;
  contact?: {
    phoneNumbers?:
      | {
          phone: string;
          description?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  home?: {
    switchLogin?: boolean | null;
    editPhone?: boolean | null;
    reloadSesion?: boolean | null;
    changePassword?: boolean | null;
    clearMac?: boolean | null;
    setCredit?: boolean | null;
    additionalService?: boolean | null;
    staticIp?: boolean | null;
    tariffPlans?: boolean | null;
    stopPlayLogin?: boolean | null;
    unlinkLogin?: boolean | null;
  };
  additional?: {
    showTask?: boolean | null;
    addFriend?: boolean | null;
    showOffice?: boolean | null;
    tv?: boolean | null;
    megogo?: boolean | null;
    showStore?: boolean | null;
    addFeedback?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  type?: ('image' | 'video' | 'pdf') | null;
  fileSize?: number | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news".
 */
export interface News {
  id: string;
  provider: 'Intelekt' | 'Opensvit' | 'Opticom' | 'Veles' | 'Mtknet';
  title: string;
  image: string | Media;
  date: string;
  author?: string | null;
  category: 'Business' | 'Info';
  preview?: string | null;
  content?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: string;
  provider: 'Intelekt' | 'Opensvit' | 'Opticom' | 'Veles' | 'Mtknet';
  title: string;
  description: string;
  displayFaq?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payments-admin".
 */
export interface PaymentsAdmin {
  id: string;
  provider: 'Intelekt' | 'Opensvit' | 'Opticom' | 'Veles' | 'Mtknet';
  name: string;
  url: string;
  img: string | Media;
  show?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tokens".
 */
export interface Token {
  id: string;
  uid: string;
  refreshToken: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "feedback".
 */
export interface Feedback {
  id: string;
  login: string;
  feedback: string;
  phone: string;
  provider: 'intelekt' | 'opensvit' | 'opticom' | 'veles' | 'mtknet';
  createdAt: string;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "passwords".
 */
export interface Password {
  id: string;
  login: string;
  password: string;
  ip: string;
  count_wrong_pass?: number | null;
  count_wrong_login?: number | null;
  all_bad_login_pass?: number | null;
  delayWait?: number | null;
  dateField?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stopPlay".
 */
export interface StopPlay {
  id: string;
  createdAt: string;
  uid: number;
  login: string;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "taskfromusers".
 */
export interface Taskfromuser {
  id: string;
  login: string;
  subLogin: string;
  message: string;
  phone: string;
  provider: 'Intelekt' | 'Opensvit' | 'Opticom' | 'Veles' | 'Mtknet';
  createdAt: string;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "login-logs".
 */
export interface LoginLog {
  id: string;
  login: string;
  timestamp: string;
  lastLoginAttempt: string;
  loginAttempts: number;
  ip: string;
  provider: string;
  method: 'login' | 'loginPhone' | 'oauth';
  loginHistory?:
    | {
        timestamp: string;
        ip: string;
        method: 'login' | 'loginPhone' | 'oauth';
        success?: boolean | null;
        clientType?: ('browser' | 'mobile' | 'desktop') | null;
        id?: string | null;
      }[]
    | null;
  loginSuccess?: boolean | null;
  sessionStatus?: ('active' | 'expired' | 'terminated') | null;
  userRole?: ('user' | 'admin' | 'moderator') | null;
  clientType?: ('browser' | 'mobile' | 'desktop') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "paymentlogs".
 */
export interface Paymentlog {
  id: string;
  route: '/getPortmoneLink' | '/getLiqPayLink' | '/getEasypayLink' | '/getPrivat24Link';
  login: string;
  suma: string;
  date: string;
  createdAt: string;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "binary-files".
 */
export interface BinaryFile {
  id: string;
  fileName: string;
  fileType: 'apk' | 'exe';
  fileSize?: number | null;
  version?: string | null;
  description?: string | null;
  platform?: ('android' | 'windows') | null;
  uploadedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "login-tracking".
 */
export interface LoginTracking {
  id: string;
  login: string;
  provider: string;
  ip?: string | null;
  date: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}